services:

  frontend:
    build: ./frontend
    container_name: pi-display-frontend
    ports:
      - "3000:5173"
    environment:
      - HOST=0.0.0.0
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: pi-display-backend
    ports:
      - "8001:8000"
    restart: unless-stopped
