services:

  frontend:
    build: ./frontend
    container_name: pi-display-frontend
    ports:
      - "3000:5173"
    environment:
      - HOST=0.0.0.0
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: pi-display-backend
    ports:
      - "8001:8000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  display:
    build: ./display
    container_name: pi-display-client
    ports:
      - "5174:5174"
    restart: unless-stopped

